version: "3.9"
services:
  mongo:
    image: bitnami/mongodb:7.0
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=rs-key
      - MONGODB_ROOT_PASSWORD=admin
      - MONGODB_USERNAME=app
      - MONGODB_PASSWORD=app
      - MONGODB_DATABASE=pfh
    ports: ["27017:27017"]
    volumes: ["mongo_data:/bitnami/mongodb"]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  kafka:
    image: bitnami/kafka:3.7
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    ports: ["9092:9092"]

volumes:
  mongo_data: