# =============================================
# 📁 ./infrastructure/monitoring/prometheus/prometheus.yml
# Prometheus Configuration (CORRIGIDO)
# =============================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'personal-finance-monitor'

rule_files:
  - "/etc/prometheus/alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Prometheus Self-Monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node.js Backend Application
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3333']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # PostgreSQL Master
  - job_name: 'postgres-master'
    static_configs:
      - targets: ['postgres-master:5432']
    scrape_interval: 30s

  # PostgreSQL Replica
  - job_name: 'postgres-replica'
    static_configs:
      - targets: ['postgres-replica:5432']
    scrape_interval: 30s

  # MongoDB Metrics (requires mongodb_exporter)
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']
    scrape_interval: 30s

  # Redis Master
  - job_name: 'redis-master'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Kafka Metrics
  - job_name: 'kafka'
    static_configs:
      - targets:
          - 'kafka-1:9101'
          - 'kafka-2:9102'
          - 'kafka-3:9103'
    scrape_interval: 30s

  # Nginx Metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s

  # Node Exporter (System Metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s